spring.datasource.url=jdbc:postgresql://localhost:5432/chatdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
# API Testing Scalar
scalar.theme=deep_space
scalar.layout=modern
scalar.documentDownloadType=both
scalar.enabled=true
scalar.url=http://localhost:8080/v3/api-docs
scalar.path=/docs
# springdoc
springdoc.swagger-ui.enabled=false
# logging
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF